--CREATE DATABASE PetStoreDb
--CREATE TABLE AvailablePets (PetId INT IDENTITY (1,1) PRIMARY KEY, Name NVARCHAR(30), Price DECIMAL(5,2), Class NVARCHAR(30), Species NVARCHAR(30));
--CREATE TABLE PetToProduct(Species NVARCHAR(30) FOREIGN KEY REFERENCES AvailablePets(Species)); 
CREATE TABLE PetProducts (ProductId INT IDENTITY (48614325,1) PRIMARY KEY, ProductName NVARCHAR (50), Price DECIMAL(5,2), 
Species NVARCHAR(30))
